volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    image: rust:1-bookworm
    volumes:
      - ../..:/workspaces:cached
    env_file:
      - .env
    command: sleep infinity
    networks:
      - app-network

  db:
    image: postgres:17-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 64M
          cpus: "0.25"
